[pytest]
addopts = -s -v
pythonpath = src
markers =
    need_review: marker for tests that need to be reviewed by a mentor
    login_guest: marker for tests related to guest login functionality
    allurefail: marker
    users: Маркировка для тестов, связанных с пользователями.
    regression: Маркировка для регрессионных тестов.
    authentication: Маркировка для тестирования аутентификация юзера